[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$major.$minor.$patch"
version_scheme = "semver"
version = "0.1.3"
update_changelog_on_bump = true
major_version_zero = true
version_files = ["VERSION"]
